## PROJET MOGPL :  La balade du robot
#### ANNEES 2025 SEMESTRE 1

(a) Donner une formulation du problème en le transformant en un problème dans
un graphe orienté.


- xr = temps de transport du robot
- D,G = action tourner gauche, tourner droite -> 1 seconde
- an = action avancer avec n nb pas avancé max 3

min xr
D+G+an<=xr

pour graphe: chaque intersection représente un noeud différente
chaque côté représente un arete (vecteur à deux sens) 
associe 1,2,3 à chaque arete liée au départ (1 : juste avancer, 2,3: avancer + tourner)
ex :         |2           |4
    1     -------  3    -----   5
    --<-- |robot| ----- |   | ------
          -------       -----
             |2           |4
ici flèche est just
exemple:

In [4]:
import numpy as np

In [5]:
#M :ligne
class Robot_resolution:
    #========== initialisation ==================
    def __init__(self,path):
        file=open(path,"r")
        self.ID_ORIENTATIONS = {d: i for i,d in enumerate(["nord","est","sud","ouest"])}
        self.list_MN = []
        self.list_matrices = []
        self.list_positions = []
        self.lire_fichier(file)

    #========== lecture fichier ===============
    def lire_fichier(self,file):
        """Lit plusieurs instances, s'arrête à '0 0'"""
        lines = [l.strip() for l in file.readlines() if l.strip() != ""]
        i = 0
        n = len(lines)

        while i < n:

            # Lecture M N
            M, N = map(int, lines[i].split())

            # Condition de fin
            if M == 0 and N == 0:
                break

            i += 1

            # Lecture matrice
            matrice = []
            row = list(map(int, lines[i].split()))

            for _ in range(M):
                if len(row) != N:
                    raise ValueError(f"Ligne matrice incorrecte : {lines[i]}")
                matrice.append(row)
                i += 1

            matrice = np.array(matrice)

            # Lecture paramètres
            parts = lines[i].split()
            if len(parts) != 5:
                raise ValueError("Paramètres D1 D2 F1 F2 direction incorrects")

            D1, D2, F1, F2 = map(int, parts[:4])
            direction = parts[4]
            i += 1
            
            self.list_MN.append((M, N))
            self.list_matrices.append(matrice)
            self.list_positions.append((D1, D2, F1, F2, direction))
    def test_init(self):
        """Affiche toutes les instances"""

        for k, ((M, N), mat, pos) in enumerate(
                zip(self.list_MN, self.list_matrices, self.list_positions)
        ):
            print(f"\n=== INSTANCE {k+1} ===")
            print(f"M, N = {M}, {N}")
            print(f"Matrice:\n{mat}")
            print(f"Position / Direction : {pos}")
        
    #============ traitement ===================
    def tourne(self,o:str="gauche"):
        idx=(self.ID_ORIENTATIONS[o]+1)%4 if o=="gauche" else (self.ID_ORIENTATIONS[o]-1)%4
        # ou self.direction = self.ID_ORIENTATIONS[idx], tous dépend de la direction
        return self.ID_ORIENTATIONS[idx]


In [6]:
r=Robot_resolution("instances.txt")
r.test_init()


=== INSTANCE 1 ===
M, N = 9, 10
Matrice:
[[0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]]
Position / Direction : (7, 2, 2, 7, 'sud')

=== INSTANCE 2 ===
M, N = 9, 10
Matrice:
[[0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]]
Position / Direction : (7, 2, 2, 7, 'sud')
